### ISSUE TITLE
Publish on Homebrew?

### ISSUE THREAD

**Issue by martin-braun** [Peter-Schorn/SoftPlayer#1]
It looks great and it would be nice, if this was available on brew.sh as a Cask.

**Comment by Peter-Schorn** [comment]
It makes no sense to publish a UI application on Homebrew. It's already available in the mac app store, which is the best place for new users to discover it.

**Comment by martin-braun** [comment]
Developers prefer to install software through package managers, this is also great for automation. Homebrew offers GUI applications via `--cask` flag, but a Homebrew formulae cannot source from the AppStore directly.

I think it would be great to have the ability to configure the `CLIENT_ID`, `TOKENS_URL` and `TOKENS_REFRESH_URL` in the settings menu of SoftPlayer and then at least upload it on GitHub under releases. 

Then, someone else could write a Homebrew Formulae that can be pushed to https://github.com/Homebrew/homebrew-cask which will enable SoftPlayer to be installed. Same goes to the SpotifyAPIServer, but it wouldn't be a Cask.
