### ISSUE TITLE
Resource heavy like animation

### ISSUE THREAD

**Issue by martin-braun** [Peter-Schorn/SoftPlayer#3]
Gorgeous like animation, but heavy on integrated graphics:

https://github.com/Peter-Schorn/SoftPlayer/assets/24259245/59eeaf4b-98b0-443d-a289-17655c3589ab

Could benefit from some optimizations or the ability to toggle the effect off at least. You can clearly see that the animation is not fluid.

**Comment by Peter-Schorn** [comment]
Yes, this animation is very resource-heavy. It's not fluid in a resource-light environment. It could certainly benefit from some optimizations, although I am not interested in the ability to disable it. A slightly laggy animation is not significantly disruptive for the user. If you use the keyboard shortcut to like/unlike the track (by default: ⌘H) the animation will not be triggered.

**Comment by martin-braun** [comment]
@Peter-Schorn I have the same problem with the library toggle: 

https://github.com/Peter-Schorn/SoftPlayer/assets/24259245/5df19fb0-d5a3-4b47-a1a0-e9e1bc9de450

This can't be bypassed by using a hotkey.

**Comment by Peter-Schorn** [comment]
Is this built in release mode?

**Comment by martin-braun** [comment]
@Peter-Schorn I archived and distributed via Developer ID (copy), so I think this is the Release build. I do disable Turbo Boost and run on integrated graphics for better battery life.

```sh
                    'c.          marty@Martins-MacBook-Pro.local
                 ,xNMM.          -------------------------------
               .OMMMMo           OS: macOS 12.6 21G115 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 21.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 6 days, 13 hours, 55 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 321 (brew), 98 (nix-user)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2048x1280@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Amethyst
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: tmux
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i9-9980HK (16) @ 2.40GHz
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 26298MiB / 65536MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

**Comment by Peter-Schorn** [comment]
I'm not going to add the option to disable these animations.

**Comment by martin-braun** [comment]
@Peter-Schorn Alright, one last question though, are you against such option fundamentally, or is it time constraints so that you have no interest in further development?

It's absolutely fine that you choose not to work on it. The product you created is already very satisfying and you offer everything to patch behavior at will. I'm just curious if you are interested in PRs or not. 

Best regards!
