### ISSUE TITLE
Ask for a CLIENT_ID - Make the server configurable in the options

### ISSUE THREAD

**Issue by martin-braun** [Peter-Schorn/SoftPlayer#4]
If no CLIENT_ID is specified, ask for it on start. This should also result in TOKENS_URL and TOKENS_REFRESH_URL to be set to localhost, since it will assume a local environment. These settings should be able to be changed in the settings dialog of the app. 

Essentially, the server should be freely configurable in the preferences of this app, because it requires editing the Info.plist to get those variables in, which is hacky if the application is already compiled.

**Comment by Peter-Schorn** [comment]
I don't understand the need to change the client id and the URLs at runtime. During development with Xcode, you can change these values and perform an incremental build very quickly. But, in general, I don't understand why you would be frequently changing these values.

If you want a truly hassle-free experience, download the app on the mac app store.

**Comment by martin-braun** [comment]
The app on the App Store uses a dedicated SpotifyAPIServer instance hosted by you, I assume. Also the App Store it not always preferred by users. 

Thanks.

**Comment by Peter-Schorn** [comment]
There are [scripts](https://github.com/Peter-Schorn/SoftPlayer/tree/main/Scripts) that can inject the client id and authorization URLs into the source code. These can also be used in the build pre- and post-actions for the scheme in Xcode:
![Screenshot 2023-05-27 at 12 42 55 AM](https://github.com/Peter-Schorn/SoftPlayer/assets/58197311/aaf18960-48fe-48b1-a853-2fee364cc102)

**Comment by martin-braun** [comment]
@Peter-Schorn Oh that's cool. I did it by editing the Info.plist which is another solution to get variables into the build. The problem is that the user has to build the app in order to get the variables into the app (or to tinker with the plist). 

Out of curiosity, would you be open for PRs that add that functionality or are you against the idea to have those parameters within the settings dialog at all?

Not implying that I can or will work on this, I got a lot of projects as well, but let's put the record straight, so everybody knows. :)

**Comment by Peter-Schorn** [comment]
I will support storing these credentials in user defaults. Then, you can set them from the command line.

**Comment by martin-braun** [comment]
@Peter-Schorn That's a nice compromise that would enable self-hosters to get started real quick. 👍

**Comment by Peter-Schorn** [comment]
Soft Player now supports user defaults for setting the authorization credentials and a compilation condition that allows it to be used without a backend server.
